name: Enforce Code Owner Reviews

on:
  pull_request_review:
    types: [submitted] # Trigger workflow when a review is submitted

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Pull Request Reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch reviews and output to a file
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            | jq -r '.[] | select(.state == "APPROVED") | .user.login' > approvals.json

          # Debug: Print approvals
          echo "Approved reviewers:"
          cat approvals.json

          # Validate that both reviewers are code owners
          CODE_OWNERS=$(cat approvals.json | grep -E "teamA|teamB" | wc -l)

          echo "Code Owner Approvals: $CODE_OWNERS"

          if [ "$CODE_OWNERS" -lt 2 ]; then
            echo "Both approvals must be from code owners!"
            exit 1
          else
            echo "Code owner validation passed."
          fi
